function cores(texto, cor)
    
    cores_rgb = struct( ...
        'vermelho',[1, 0, 0], ...
        'verde',[0, 1, 0], ...
        'amarelo',[1, 1, 0], ...
        'azul',[0, 0, 1], ...
        'magenta',[1, 0, 1], ...
        'ciano',[0, 1, 1]);

    if isfield(cores_rgb, cor)
        cprintf(cores_rgb.(cor),'%s\n', texto);
    else
        disp(texto);
    end
end