
funcao_str = input('Digite a função que deseja plotar: ','s');
a = input('Digite o valor inicial do intervalo que deseja mostrar: ');
b = input('Digite o segundo valor do intervalo que deseja mostrar: ');
f_func = str2func(['@(x)', funcao_str]);
cor = input(['Digite a cor que deseja.\n' ...
    'r para vermelho\n' ...
    'g para verde\n' ...
    'b para azul\n' ...
    'c para ciano\n' ...
    'm para magenta\n' ...
    'y para amarelo\n' ...
    'k para preto\n' ...
    'w para branco\n' ...
    'Digite: '],'s');

figure;
hold on;
fplot(f_func, [a, b], cor, 'LineWidth', 1.5);
xlabel('x');
ylabel('y');
title('Funções Plotadas');
grid('on');

resp = 's';

while resp == 's'
    resp = input('Quer plotar outro gráfico? s para sim e qualquer outro valor para não: ','s');
    if resp ~= 's'
        break
    end
    
    funcao_str = input('Digite a função que deseja plotar: ','s');
    a = input('Digite o valor inicial do intervalo que deseja mostrar: ');
    b = input('Digite o segundo valor do intervalo que deseja mostrar: ');
    f_func = str2func(['@(x)', funcao_str]);
    cor = input(['Digite a cor que deseja.\n' ...
    'r para vermelho\n' ...
    'g para verde\n' ...
    'b para azul\n' ...
    'c para ciano\n' ...
    'm para magenta\n' ...
    'y para amarelo\n' ...
    'k para preto\n' ...
    'w para branco\n' ...
    'Digite: '],'s');

    fplot(f_func, [a, b], cor, 'LineWidth', 1.5);
end

